#!/bin/bash

#set -x

pg_port=""

DOCKER_COMPOSE_TEMPLATE_DIR=docker-compose-template

function usage {
   cat <<EOF
Usage: $0 --tag <sq_docker_tag> --sq_port <sq_port> --pg_port <pg_port> --pg_backup <backup_file>

--tag: Sonar Tag, default lts-enterprise
--sq_port: Sonar port, default 9000
--pg_port: Postgres port, default sonar port less 4000
--pg_backup: Postgres back DB to restore, default db.backup 

EOF

}

sq_tag=lts-enterprise
pg_tag=pg_lts-enterprise
sq_port=9000
pg_backup=db.backup
id=$$

while [ $# -ne 0 ]; do
   case $1 in
      --tag)
         shift
         sq_tag=$1
         pg_tag="pg_$(echo $sq_tag | sed 's/:/_/')"
         ;;
      --port)
         shift
         sq_port=$1
         ;;
      --pg_port)
         shift
         pg_port=$1
         ;;
      --pg_backup)
         shift
         pg_backup=$1
         ;;
      *)
         echo "ERROR: Unexpected parameter $1" && usage
         exit 1
         ;;
   esac
   shift
done

[ "$pg_port" = "" ] && pg_port=$(expr $sq_port - 4000)

echo "Creating SonarQube instance with tag $sq_tag"

temp_dir=$id-sonar
echo "Creating temp dir $temp_dir"
cp -r $DOCKER_COMPOSE_TEMPLATE_DIR $temp_dir
cat $DOCKER_COMPOSE_TEMPLATE_DIR/.env | \
   sed -e "s/SONAR_PORT=9000/SONAR_PORT=$sq_port/" \
       -e "s/SONAR_TAG=.*/SONAR_TAG=$sq_tag/" \
       -e "s/SONAR_CONTAINER=sonar_lts/SONAR_CONTAINER=${id}_sonar/" \
       -e "s/POSTGRES_PORT=5432/POSTGRES_PORT=$pg_port/" \
       -e "s/POSTGRES_CONTAINER=db_lts/POSTGRES_CONTAINER=${id}_db/" \
   > $temp_dir/.env

echo "Starting Sonar instance"
docker compose -f $temp_dir/docker-compose.yml up -d
sleep 30

echo "Restoring DB"
pg_restore --host localhost --port $pg_port --username sonar -d sonar --verbose --clean "$pg_backup" >/dev/null

echo "Regenerating index"
# cd $temp_dir; docker compose down; cd -
# sleep 5
# rm -rf $temp_dir/sonar/data/es7 $temp_dir/sonar/data/es8
docker exec -it ${id}_sonar rm -rf data/es7 data/es8
cd $temp_dir; docker compose down; docker compose up -d; cd -

sleep 20
echo "Ready, please browse to http://localhost:$sq_port"
