[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "sonar-tools"
version = "3.14"
description = "A collection of utility scripts for SonarQube Server or Cloud"
readme = "README.md"

requires-python = ">= 3.8"

dependencies = [
    "argparse",
    "datetime",
    "python-dateutil",
    "requests",
    "jprops",
    "levenshtein",
    "PyYAML"
]

authors = [
  {name = "Olivier Korach", email = "olivier.korach@gmail.com"},
]
maintainers = [
  {name = "Olivier Korach", email = "olivier.korach@gmail.com"},
]
keywords = ["sonarqube", "sonar", "utilities"]

classifiers = [
    "Development Status :: 5 - Production/Styable",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "License :: OSI Approved :: GNU Lesser General Public License v3 or later (LGPLv3+)",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]

license = "LGPL-3.0-or-later"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://pypi.org/project/sonar-tools/"
Repository = "https://github.com/okorach/sonar-tools.git"
Issues = "https://github.com/okorach/sonar-tools/issues"
Changelog = "https://github.com/okorach/sonar-tools/blob/master/doc/CHANGELOG.md"

[project.scripts]
sonar-audit = "cli.audit:main"
sonar-projects-export = "cli.projects_export:main"
sonar-projects-import = "cli.projects_import:main"
sonar-projects = "cli.projects_cli:main"
sonar-measures-export = "cli.measures_export:main"
sonar-housekeeper = "cli.housekeeper:main"
sonar-issues-sync = "cli.findings_sync:main"
sonar-findings-sync = "cli.findings_sync:main"
sonar-custom-measures = "cli.cust_measures:main"
sonar-issues-export = "cli.findings_export:main"
sonar-findings-export = "cli.findings_export:main"
sonar-loc = "cli.loc:main"
sonar-config = "cli.config:main"
support-audit = "cli.support:main"
sonar-rules = "cli.rules_cli:main"
