#!/usr/bin/env python3

print('''Collections of utilities for SonarQube:
- sonar-audit: Audits a SonarQube platform for bad practices, performance, configuration problems
- sonar-housekeeper: Deletes projects that have not been analyzed since a given number of days
- sonar-measures-export: Exports measures/metrics of one, several or all projects of the platform i CSV
- sonar-issues-export: Exports issues (potentially filtered) from the platform in CSV
- sonar-projects-export: Exports all projects from a platform (EE and higher)
- sonar-projects-import: Imports a list of projects into a platform (EE and higher)
See tools built-in -h help and https://github.com/okorach/sonarqube-tools for more documentation
''')