#!/usr/bin/env python3
#
# sonar-tools
# Copyright (C) 2019-2020 Olivier Korach
# mailto:olivier.korach AT gmail DOT com
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
print('''Collections of utilities for SonarQube:
- sonar-audit: Audits a SonarQube platform for bad practices, performance, configuration problems
- sonar-housekeeper: Deletes projects that have not been analyzed since a given number of days
- sonar-measures-export: Exports measures/metrics of one, several or all projects of the platform in CSV
- sonar-issues-export: Exports issues (potentially filtered) from the platform in CSV
- sonar-issues-sync: Synchronizes issues between 2 branches, or 2 projects
- sonar-projects-export: Exports all projects from a platform (EE and higher)
- sonar-projects-import: Imports a list of projects into a platform (EE and higher)
See tools built-in -h help and https://github.com/okorach/sonarqube-tools for more documentation
''')